import sympy as sp

import mathgr
from mathgr.gr import CovD, R, UseMetric
from mathgr.tensor import DE, DN, UP, Pd, Pm2, tensor


def test_typeset_public_api_applies_hooks_template_flag_and_prints(capsys):
    import mathgr.typeset as typeset

    x, y = sp.symbols("x y")
    previous_hooks = tuple(typeset.ToTeXHook)
    previous_template = typeset.ToTeXTemplate

    try:
        typeset.ToTeXHook[:] = [{x: y}]
        typeset.ToTeXTemplate = False

        assert typeset.ToTeXString(x + 1) == "y\n + 1"
        assert typeset.ToTeX(y + 1) is None
        assert capsys.readouterr().out == "y\n + 1\n"
        assert mathgr.ToTeXString(x + 1) == "y\n + 1"

        typeset.ToTeXTemplate = True
        tex = typeset.ToTeXString(x)
        assert tex.startswith("%Generated by MathGR/typeset.m, ")
        assert "\\begin{dmath}" in tex
        assert tex.endswith("\\end{document}\n")
    finally:
        typeset.ToTeXHook[:] = previous_hooks
        typeset.ToTeXTemplate = previous_template


def test_typeset_addition_renders_negative_terms_as_subtractions_like_upstream():
    import mathgr.typeset as typeset

    x, y, z = sp.symbols("xTexSigns yTexSigns zTexSigns")
    previous_template = typeset.ToTeXTemplate

    try:
        typeset.ToTeXTemplate = False

        tex = typeset.ToTeXString(x + z - y)

        assert "\n + \n -" not in tex
        assert tex == "xTexSigns\n - yTexSigns\n + zTexSigns"
    finally:
        typeset.ToTeXTemplate = previous_template


def test_typeset_hook_accepts_sympy_wild_pattern_rules_like_upstream_replacements():
    import mathgr.typeset as typeset

    f = tensor("fToTeXHookPattern")
    g = tensor("gToTeXHookPattern")
    i = sp.Wild("i")
    previous_hooks = tuple(typeset.ToTeXHook)
    previous_template = typeset.ToTeXTemplate

    try:
        typeset.ToTeXHook[:] = [(f(DN(i)), lambda i: g(DN(f"{i}_tex")))]
        typeset.ToTeXTemplate = False

        assert typeset.ToTeXString(f(DN("a")) + f(DN("b"))) == (
            "gToTeXHookPattern_{a_tex}\n + gToTeXHookPattern_{b_tex}"
        )
    finally:
        typeset.ToTeXHook[:] = previous_hooks
        typeset.ToTeXTemplate = previous_template


def test_typeset_callable_hook_recurs_into_subexpressions_like_upstream_replace_repeated():
    import mathgr.typeset as typeset

    x, y, z = sp.symbols("xTexCallable yTexCallable zTexCallable")
    previous_hooks = tuple(typeset.ToTeXHook)
    previous_template = typeset.ToTeXTemplate

    def hook(expr):
        return y if expr == x else expr

    try:
        typeset.ToTeXHook[:] = [hook]
        typeset.ToTeXTemplate = False

        assert typeset.ToTeXString(x * z + 1) == "yTexCallable zTexCallable\n + 1"
    finally:
        typeset.ToTeXHook[:] = previous_hooks
        typeset.ToTeXTemplate = previous_template


def test_typeset_renders_mathgr_tensor_derivatives_and_pm2_without_internal_names():
    from mathgr.typeset import ToTeXString
    import mathgr.typeset as typeset

    f = tensor("fTypeset")
    x = sp.Symbol("x")
    previous_template = typeset.ToTeXTemplate

    try:
        typeset.ToTeXTemplate = False

        assert ToTeXString(f(UP("a"), DN("b"))) == "fTypeset^{a}_{b}"
        assert ToTeXString(Pd(x, DE(0))) == "\\dot{x}"
        assert ToTeXString(Pd(Pd(x, DE(0)), DE(0))) == "\\ddot{x}"
        assert ToTeXString(Pd(x, DN("i"))) == "\\partial_{i} x"
        assert ToTeXString(Pm2(x, DN)) == "\\partial^{-2}\\left(x\\right)"
    finally:
        typeset.ToTeXTemplate = previous_template


def test_typeset_renders_tensor_valued_riemann_without_internal_names():
    from mathgr.tensor import LatinIdx, declare_idx
    from mathgr.typeset import ToTeXString
    import mathgr.typeset as typeset

    u, d = declare_idx("texRiemannU", "texRiemannD", dim=4, index_set=LatinIdx, color="Black")
    metric = tensor("gTypesetRiemann")
    previous_template = typeset.ToTeXTemplate

    try:
        typeset.ToTeXTemplate = False
        UseMetric(metric, (u, d))

        lower_riemann = R(d("a"), d("b"), d("c"), d("d"))

        assert ToTeXString(lower_riemann) == "R_{abcd}"
        assert ToTeXString(CovD(lower_riemann, d("e"))) == "\\nabla_{e} R_{abcd}"
    finally:
        typeset.ToTeXTemplate = previous_template


def test_typeset_renders_active_levicivita_without_internal_names():
    from mathgr.tensor import LatinIdx, LeviCivita, declare_idx
    from mathgr.typeset import ToTeXString
    import mathgr.typeset as typeset

    u, d = declare_idx("texLeviCivitaU", "texLeviCivitaD", dim=3, index_set=LatinIdx, color="Black")
    previous_template = typeset.ToTeXTemplate

    try:
        typeset.ToTeXTemplate = False

        assert ToTeXString(LeviCivita(u("a"), u("b"), u("c"))) == "LeviCivita^{abc}"
        assert ToTeXString(LeviCivita(d("a"), d("b"), d("c"))) == "LeviCivita_{abc}"
    finally:
        typeset.ToTeXTemplate = previous_template


def test_typeset_renders_delta_indices_in_upstream_variance_order():
    from mathgr.tensor import Dta
    from mathgr.typeset import ToTeXString
    import mathgr.typeset as typeset

    previous_template = typeset.ToTeXTemplate

    try:
        typeset.ToTeXTemplate = False

        assert ToTeXString(Dta(UP("a"), DN("b"))) == r"\delta_{b}^{a}"
        assert ToTeXString(Dta(DN("b"), UP("a"))) == r"\delta_{b}^{a}"
        assert ToTeXString(Dta(UP("a"), UP("b"))) == r"\delta^{a}^{b}"
        assert ToTeXString(Dta(DN("a"), DN("b"))) == r"\delta_{a}_{b}"
    finally:
        typeset.ToTeXTemplate = previous_template


def test_typeset_keeps_explicit_time_derivative_on_pm2_like_upstream():
    from mathgr.typeset import ToTeXString
    import mathgr.typeset as typeset

    x = sp.Symbol("x")
    previous_template = typeset.ToTeXTemplate

    try:
        typeset.ToTeXTemplate = False

        assert ToTeXString(Pd(Pm2(x, DN), DE(0))) == "\\partial_{0} \\partial^{-2}\\left(x\\right)"
    finally:
        typeset.ToTeXTemplate = previous_template


def test_decorate_tex_string_matches_upstream_text_cleanup_and_arrow_breaks():
    import mathgr.typeset as typeset

    previous_template = typeset.ToTeXTemplate
    try:
        typeset.ToTeXTemplate = False

        assert typeset.DecorateTeXString(r"\text{lhs} + x\to y$") == "lhs \n +  x\n \\to  y"
    finally:
        typeset.ToTeXTemplate = previous_template


def test_decorate_tex_string_matches_upstream_raw_sign_line_breaks():
    import mathgr.typeset as typeset

    previous_template = typeset.ToTeXTemplate
    try:
        typeset.ToTeXTemplate = False

        assert typeset.DecorateTeXString(r"a+b-c{-d") == "a\n + b\n - c{-d"
        assert typeset.DecorateTeXString("a\n-b") == "a\n-b"
    finally:
        typeset.ToTeXTemplate = previous_template


def test_decorate_tex_string_matches_upstream_waste_and_time_dot_cleanup():
    import mathgr.typeset as typeset

    previous_template = typeset.ToTeXTemplate
    try:
        typeset.ToTeXTemplate = False

        assert typeset.DecorateTeXString(r"\partial_0\partial_0 f(x){}^2") == r"\ddot f(x)^2"
        assert typeset.DecorateTeXString(r"\partial^{-2}\left(x\right) + \partial_0 y") == (
            r"\partial^{-2}\left(x\right)"
            " \n +  "
            r"\partial_0 y"
        )
    finally:
        typeset.ToTeXTemplate = previous_template
