import sympy as sp
import pytest
from collections import Counter

from examples.decomp_example import main
from examples.general_presentation import main as general_presentation_main
from mathgr.decomp import DTot, Decomp0i, UTot
from mathgr.tensor import DE, DN, UE, UP, Index, tensor


def test_decomp_example_ports_named_notebook_results():
    f = tensor("f")
    h0, h1 = sp.symbols("h0 h1")
    from mathgr.gr import R
    from mathgr.tensor import Simp

    results = main()
    expected = {
        "simple": f(UE(0), DE(0)) + f(UP("mu"), DN("mu")),
        "simple_simplified": f(UE(0), DE(0)) + f(UP("a"), DN("a")),
        "hook_replacement": h0 + UP.dim * h1,
        "sqrt": sp.sqrt(1 + f(DE(0)) * f(UE(0)) + f(DN("a")) * f(UP("a"))),
        "metric_noop": Decomp0i(Simp(R())),
    }

    for key, value in expected.items():
        assert results[key] == value


def test_decomp_example_ports_local_withmetric_metric_decomposition_cell():
    results = main()
    metric = tensor("metricDecompExample")

    metric_decomposition = results["metric_decomposition"]

    assert not metric_decomposition.has(UTot("a"), DTot("a"))
    assert metric_decomposition.has(metric(UE(0), UE(0)))
    assert metric_decomposition.has(metric(DE(0), DE(0)))
    assert metric_decomposition.has(metric(UP("a"), UP("b")))
    assert metric_decomposition.has(metric(DN("a"), DN("b")))


def test_general_presentation_ports_initial_ricci_scalar_cell():
    from mathgr.gr import R, Rsimp
    from mathgr.tensor import Simp

    results = general_presentation_main()

    assert results["ricci_scalar"] == Simp(R())
    assert results["ricci_scalar"] == Rsimp()


def test_general_presentation_ports_ricci_scalar_totex_cell():
    results = general_presentation_main()
    tex = results["ricci_scalar_tex"]

    assert tex.startswith("%Generated by MathGR/typeset.m, ")
    assert "\\begin{dmath}" in tex
    assert "\\partial_{" in tex
    assert "g^{" in tex
    assert "_TensorCall" not in tex
    assert "_PdT" not in tex


def test_general_presentation_ports_second_bianchi_cells():
    results = general_presentation_main()

    assert results["second_bianchi"] == 0
    assert results["second_bianchi_simplified"] == 0


def test_general_presentation_ports_derivative_second_bianchi_cells():
    results = general_presentation_main()

    assert results["derivative_second_bianchi"] == 0
    assert results["derivative_second_bianchi_simplified"] == 0


def test_newton_gauge_example_ports_initial_metric_setup_cells():
    from examples import newton_gauge
    from mathgr.tensor import Dta, Pd, PdT, PdVars
    from mathgr.util import Eps

    results = newton_gauge.main()

    assert results["sqrtg"] == newton_gauge.a**4 * sp.sqrt(
        (1 + 2 * Eps * newton_gauge.phi) * (1 - 2 * Eps * newton_gauge.psi) ** 3
    )
    assert results["spatial_metric_down"] == (
        -newton_gauge.a**2 * (1 - 2 * Eps * newton_gauge.psi) * Dta(DN("i"), DN("j"))
    )
    assert results["spatial_metric_up"] == (
        -Dta(DN("i"), DN("j")) / (newton_gauge.a**2 * (1 - 2 * Eps * newton_gauge.psi))
    )
    assert results["metric_00"] == newton_gauge.a**2 * (1 + 2 * Eps * newton_gauge.phi)
    assert results["metric_0i"] == 0
    assert results["inverse_metric_00"] == 1 / (newton_gauge.a**2 * (1 + 2 * Eps * newton_gauge.phi))
    assert results["inverse_metric_0i"] == 0
    assert results["background_time_derivative"] == newton_gauge.a * newton_gauge.H
    assert results["background_second_time_derivative"] == newton_gauge.a * newton_gauge.H**2 + newton_gauge.a * newton_gauge.dH
    assert results["background_spatial_derivative"] == 0
    assert newton_gauge.Simp(Pd(newton_gauge.phi0, DN("i"))) == 0
    assert newton_gauge.Simp(PdT(newton_gauge.a, PdVars(DN("i")))) == 0


def test_newton_gauge_metric_decomposition_uses_rule_table():
    from examples import newton_gauge
    from mathgr.util import Eps

    assert len(newton_gauge.metric_rules) == 8
    assert newton_gauge.decomp_hook(newton_gauge.g(DN("i"), DN("j"))) == (
        -newton_gauge.a**2 * (1 - 2 * Eps * newton_gauge.psi) * newton_gauge.Dta(DN("i"), DN("j"))
    )
    assert newton_gauge.decomp_hook(newton_gauge.g(DE(0), DN("i"))) == 0
    assert newton_gauge.decomp_hook(newton_gauge.g(UE(0), UP("i"))) == 0


def test_newton_gauge_example_ports_local_decompg2h_and_action_cell():
    from examples import newton_gauge
    from mathgr.gr import V, X
    from mathgr.tensor import Pd
    from mathgr.util import Eps

    field = newton_gauge.phi0 + Eps * newton_gauge.delta_phi
    decomposed_kinetic = newton_gauge.DecompG2H(lambda: X(field))
    results = newton_gauge.main(compute_action=False)

    assert not decomposed_kinetic.has(DTot("a"), UTot("a"))
    assert decomposed_kinetic.has(Pd(newton_gauge.delta_phi, DE(0)))
    assert decomposed_kinetic.has(Pd(newton_gauge.phi0, DE(0)))
    assert decomposed_kinetic.has(Pd(newton_gauge.delta_phi, DN("a")))
    assert not decomposed_kinetic.has(Pd(newton_gauge.phi0, DN("a")))
    assert results["action_density"].has(V(field))
    assert results["action_density"].has(newton_gauge.Sqrtg)
    assert not results["action_density"].has(DTot("a"), UTot("a"))


@pytest.mark.slow
def test_newton_gauge_example_ports_background_and_linear_action_cells():
    from examples import newton_gauge
    from mathgr.gr import V
    from mathgr.tensor import Pd

    results = newton_gauge.main(compute_action=True)
    phi0_dot = Pd(newton_gauge.phi0, DE(0))

    expected_s0 = (
        3 * newton_gauge.a**2 * newton_gauge.dH
        + 3 * newton_gauge.a**2 * newton_gauge.H**2
        + newton_gauge.a**2 * phi0_dot**2 / 2
        - newton_gauge.a**4 * V(newton_gauge.phi0)
    )
    expected_s1 = (
        -3 * newton_gauge.a**2 * newton_gauge.dH * newton_gauge.phi
        - 3 * newton_gauge.a**2 * newton_gauge.H**2 * newton_gauge.phi
        - 9 * newton_gauge.a**2 * newton_gauge.dH * newton_gauge.psi
        - 9 * newton_gauge.a**2 * newton_gauge.H**2 * newton_gauge.psi
        - 3 * newton_gauge.a**2 * newton_gauge.H * Pd(newton_gauge.phi, DE(0))
        - newton_gauge.a**2 * Pd(Pd(newton_gauge.phi, DN("a")), DN("a"))
        + newton_gauge.a**2 * Pd(newton_gauge.delta_phi, DE(0)) * phi0_dot
        - newton_gauge.a**2 * newton_gauge.phi * phi0_dot**2 / 2
        - 3 * newton_gauge.a**2 * newton_gauge.psi * phi0_dot**2 / 2
        - 9 * newton_gauge.a**2 * newton_gauge.H * Pd(newton_gauge.psi, DE(0))
        - 3 * newton_gauge.a**2 * Pd(Pd(newton_gauge.psi, DE(0)), DE(0))
        + 2 * newton_gauge.a**2 * Pd(Pd(newton_gauge.psi, DN("a")), DN("a"))
        - newton_gauge.a**4 * newton_gauge.delta_phi * sp.diff(V(newton_gauge.phi0), newton_gauge.phi0)
        - newton_gauge.a**4 * newton_gauge.phi * V(newton_gauge.phi0)
        + 3 * newton_gauge.a**4 * newton_gauge.psi * V(newton_gauge.phi0)
    )

    assert newton_gauge.Simp(results["s0"] - expected_s0) == 0
    assert newton_gauge.Simp(results["s1"] - expected_s1) == 0


@pytest.mark.slow
def test_newton_gauge_quadratic_action_keeps_spatial_indices_fully_contracted():
    from examples import newton_gauge

    s2 = newton_gauge.action_order(2)

    for term in sp.Add.make_args(sp.expand(s2)):
        counts = _implicit_index_label_counts(term)
        assert all(count != 1 for count in counts.values()), term


@pytest.mark.slow
def test_newton_gauge_example_ports_displayed_quadratic_action_cell():
    from examples import newton_gauge
    from mathgr.gr import V
    from mathgr.tensor import Pd

    results = newton_gauge.main(compute_action=True)
    s2 = sp.expand(results["s2"])
    phi0_dot = Pd(newton_gauge.phi0, DE(0))
    expected_terms = [
        9 * newton_gauge.a**2 * newton_gauge.dH * newton_gauge.phi**2 / 2,
        9 * newton_gauge.a**2 * newton_gauge.H**2 * newton_gauge.phi**2 / 2,
        9 * newton_gauge.a**2 * newton_gauge.dH * newton_gauge.phi * newton_gauge.psi,
        newton_gauge.a**2 * Pd(newton_gauge.delta_phi, DE(0)) ** 2 / 2,
        -newton_gauge.a**2 * Pd(newton_gauge.delta_phi, DN("a")) ** 2 / 2,
        -newton_gauge.a**4
        * newton_gauge.delta_phi
        * newton_gauge.phi
        * sp.diff(V(newton_gauge.phi0), newton_gauge.phi0),
        3 * newton_gauge.a**4 * newton_gauge.phi * newton_gauge.psi * V(newton_gauge.phi0),
        3 * newton_gauge.a**2 * newton_gauge.phi * newton_gauge.psi * phi0_dot**2 / 2,
    ]

    assert newton_gauge.Simp(s2 - newton_gauge.action_order(2)) == 0
    for term in expected_terms:
        assert term in sp.Add.make_args(s2)


def test_second_order_gw_pert_example_ports_metric_setup_cells():
    from examples import second_order_gw_pert
    from mathgr.tensor import Dta, PdT, PdVars
    from mathgr.util import Eps

    results = second_order_gw_pert.main(compute_action=False)
    dummy = DN("a")

    assert results["sqrtg"] == second_order_gw_pert.a**3
    assert results["shift"] == 0
    assert results["spatial_metric_down"] == second_order_gw_pert.a**2 * (
        Dta(DN("i"), DN("j"))
        + Eps * second_order_gw_pert.gamma(DN("i"), DN("j"))
        + Eps**2
        * second_order_gw_pert.gamma(DN("i"), dummy)
        * second_order_gw_pert.gamma(dummy, DN("j"))
        / 2
    )
    assert results["spatial_metric_up"] == (
        Dta(DN("i"), DN("j"))
        - Eps * second_order_gw_pert.gamma(DN("i"), DN("j"))
        + Eps**2
        * second_order_gw_pert.gamma(DN("i"), dummy)
        * second_order_gw_pert.gamma(dummy, DN("j"))
        / 2
    ) / second_order_gw_pert.a**2
    assert second_order_gw_pert.gamma(DN("i"), DN("i")) == 0
    assert second_order_gw_pert.Simp(second_order_gw_pert._gamma_raw(DN("i"), DN("i"))) == 0
    assert second_order_gw_pert.Simp(
        PdT(second_order_gw_pert._gamma_raw(DN("i"), DN("i")), PdVars(DE(0)))
    ) == 0
    assert second_order_gw_pert.Simp(
        PdT(second_order_gw_pert.gamma(DN("i"), DN("j")), PdVars(DN("i")))
    ) == 0
    assert results["metric_00"] == -1
    assert results["metric_0i"] == 0
    assert results["inverse_metric_00"] == -1
    assert results["inverse_metric_0i"] == 0


@pytest.mark.slow
def test_second_order_gw_pert_example_ports_final_quadratic_action_cell():
    from examples import second_order_gw_pert
    from mathgr.tensor import Pd

    results = second_order_gw_pert.main(compute_action=True)
    expected = (
        second_order_gw_pert.Mp**2
        * second_order_gw_pert.a**3
        * Pd(second_order_gw_pert.gamma(DN("a"), DN("b")), DE(0)) ** 2
        / 8
        - second_order_gw_pert.Mp**2
        * second_order_gw_pert.a
        * Pd(second_order_gw_pert.gamma(DN("a"), DN("b")), DN("c")) ** 2
        / 8
    )

    assert second_order_gw_pert.Simp(results["s_full"] - expected) == 0


def test_second_order_pert_example_ports_zeta_gauge_action_setup_cells():
    from examples import second_order_pert
    import mathgr.gr as gr_module
    from mathgr.util import OO
    from mathgr.frwadm import Fourier2, LapseN, ShiftN, Sqrtg
    from mathgr.tensor import Pd, PdT, PdVars, is_pdt, pdt_parts, tensor_head_name

    results = second_order_pert.main(compute_action=False)

    assert results["gauge"] == "zeta"
    assert results["sqrtg"] == Sqrtg
    assert results["lapse"] == LapseN
    assert results["shift"] == ShiftN(DN("i"))
    assert second_order_pert.Simp(Pd(second_order_pert.phi, DN("i"))) == 0
    assert second_order_pert.Simp(PdT(second_order_pert.phi, PdVars(DN("i"), DE(0)))) == 0
    assert results["action_density"].has(second_order_pert.phi)
    assert not results["action_density"].has(gr_module.LapseN)
    assert not any(tensor_head_name(node) == "ShiftN" for node in sp.preorder_traversal(results["action_density"]))

    second_order_pre_fourier = OO(2, op=second_order_pert.Simp)(second_order_pert.action_density(simplify=True))
    assert not any(getattr(node, "func", None).__name__ == "_Dta" for node in sp.preorder_traversal(second_order_pre_fourier))

    second_order_fourier = Fourier2(second_order_pre_fourier)
    assert not any(
        is_pdt(node) and tensor_head_name(pdt_parts(node)[0]) == "b"
        for node in sp.preorder_traversal(second_order_fourier)
    )


@pytest.mark.slow
def test_second_order_pert_example_ports_final_zeta_gauge_action_cell():
    from examples import second_order_pert
    from mathgr.tensor import Pd

    expected = (
        -second_order_pert.a * second_order_pert.k**2 * second_order_pert.epsilon * second_order_pert.zeta**2
        + second_order_pert.a**3 * second_order_pert.epsilon * Pd(second_order_pert.zeta, DE(0)) ** 2
    )

    assert second_order_pert.Simp(second_order_pert.second_order_action() - expected) == 0


def test_second_order_pert_deltaphi_gauge_example_ports_initial_cells():
    from examples import second_order_pert_deltaphi_gauge
    from mathgr.tensor import Pd, PdT, PdVars
    from mathgr.util import Eps

    results = second_order_pert_deltaphi_gauge.main(compute_action=False)

    assert results["gauge"] == "delta_phi"
    assert results["phi"] == second_order_pert_deltaphi_gauge.phi0 + Eps * second_order_pert_deltaphi_gauge.varphi
    assert results["zeta"] == 0
    assert second_order_pert_deltaphi_gauge.Simp(Pd(second_order_pert_deltaphi_gauge.phi0, DN("i"))) == 0
    assert second_order_pert_deltaphi_gauge.Simp(
        PdT(second_order_pert_deltaphi_gauge.phi0, PdVars(DN("i"), DE(0)))
    ) == 0
    assert not results["action_density"].has(second_order_pert_deltaphi_gauge.zeta)


def test_third_order_pert_examples_port_zeta_gauge_action_setup_cells():
    from examples import third_order_pert, third_order_pert_pm2
    from mathgr.frwadm import Sqrtg
    from mathgr.util import Eps
    from mathgr.util import OO

    results = third_order_pert.main(compute_orders=False)
    pm2_results = third_order_pert_pm2.main(compute_orders=False)

    assert results["gauge"] == "zeta"
    assert results["sqrtg"] == Sqrtg
    assert results["action_density"].has(third_order_pert.phi)
    assert results["order_operator"](1 + 2 * Eps + 3 * Eps**2 + 4 * Eps**3) == 4
    assert pm2_results["gauge"] == "zeta"
    assert pm2_results["uses_pm2_constraints"] is True
    assert pm2_results["action_density"].has(third_order_pert_pm2.phi)
    assert pm2_results["order_operator"](1 + 2 * Eps + 3 * Eps**2 + 4 * Eps**3) == 4


def test_gauge_transform_example_ports_initial_helpers():
    from examples import gauge_trans_df_to_zeta
    from mathgr.tensor import Pd, PdT, PdVars
    from mathgr.util import Eps

    results = gauge_trans_df_to_zeta.main()
    dummy = DN("a")

    assert results["default_dim"] == 3
    assert gauge_trans_df_to_zeta.Simp(Pd(gauge_trans_df_to_zeta.phi0, DN("i"))) == 0
    assert gauge_trans_df_to_zeta.Simp(Pd(gauge_trans_df_to_zeta.a, DN("i"))) == 0
    assert gauge_trans_df_to_zeta.Simp(Pd(gauge_trans_df_to_zeta.H, DE(0))) == (
        -gauge_trans_df_to_zeta.epsilon * gauge_trans_df_to_zeta.H**2
    )
    assert results["expanded_a"] == sp.expand(
        gauge_trans_df_to_zeta.a
        + Eps * gauge_trans_df_to_zeta.a * gauge_trans_df_to_zeta.H * gauge_trans_df_to_zeta.delta_t
        + Eps**2
        * (gauge_trans_df_to_zeta.a * gauge_trans_df_to_zeta.H**2 - gauge_trans_df_to_zeta.a * gauge_trans_df_to_zeta.H**2 * gauge_trans_df_to_zeta.epsilon)
        * gauge_trans_df_to_zeta.delta_t**2
        / 2
    )
    assert results["expanded_field"].has(gauge_trans_df_to_zeta.delta_x(dummy))
    assert results["expanded_field"].has(Pd(gauge_trans_df_to_zeta.varphi, dummy))
    assert results["collected"](1 + Eps * gauge_trans_df_to_zeta.varphi + Eps * gauge_trans_df_to_zeta.phi0) == (
        1 + Eps * (gauge_trans_df_to_zeta.phi0 + gauge_trans_df_to_zeta.varphi)
    )


def test_zeta_gauge_action_from_delta_phi_example_ports_setup_and_constraints():
    from examples import zeta_gauge_action_from_delta_phi
    from mathgr.frwadm import alpha, b, beta, zeta
    from mathgr.tensor import Pd, PdT, PdVars
    from mathgr.util import Eps

    results = zeta_gauge_action_from_delta_phi.main(compute_action=False)
    constraints = results["constraints"]

    assert results["phi"] == zeta_gauge_action_from_delta_phi.phi0 + Eps * zeta_gauge_action_from_delta_phi.varphi
    assert results["zeta"] == 0
    assert zeta_gauge_action_from_delta_phi.Simp(Pd(zeta_gauge_action_from_delta_phi.phi0, DN("i"))) == 0
    assert zeta_gauge_action_from_delta_phi.Simp(
        PdT(zeta_gauge_action_from_delta_phi.phi0, PdVars(DN("i"), DE(0)))
    ) == 0
    assert constraints[alpha].has(zeta_gauge_action_from_delta_phi.varphi)
    assert constraints[beta].has(zeta_gauge_action_from_delta_phi.varphi)
    assert constraints[b(DN("a"))] == 0
    assert not results["action_density"].has(zeta)


def test_zeta_gauge_action_from_delta_phi_example_ports_selected_cubic_tex_cell():
    from examples import zeta_gauge_action_from_delta_phi
    from mathgr.frwadm import a, epsilon
    from mathgr.tensor import Pd, Pm2

    results = zeta_gauge_action_from_delta_phi.main(compute_action=False)
    zeta_n = zeta_gauge_action_from_delta_phi.zeta_n
    expected = (
        -2
        * a**3
        * epsilon**2
        * Pd(Pd(Pm2(zeta_n, DN), DE(0)), DN("a"))
        * Pd(zeta_n, DE(0))
        * Pd(zeta_n, DN("a"))
        + a**3 * epsilon**2 * zeta_n * Pd(zeta_n, DE(0)) ** 2
        + a * epsilon**2 * zeta_n * Pd(zeta_n, DN("a")) ** 2
    )

    assert results["s3_select"] == expected
    assert zeta_gauge_action_from_delta_phi.count_slow_roll_order(expected.args[0]) == 2
    assert results["s3_select_tex"].startswith("%Generated by MathGR/typeset.m, ")
    assert "\\begin{dmath}" in results["s3_select_tex"]
    assert "\\partial^{-2}" in results["s3_select_tex"]
    assert "\\zeta_{n}" in results["s3_select_tex"]
    assert "\n + \n -" not in results["s3_select_tex"]
    assert "_PdT" not in results["s3_select_tex"]


def test_equilateral_example_ports_initial_kinetic_expansion_cells():
    from examples import equilateral

    results = equilateral.main()
    delta = equilateral.delta_phi(equilateral.x, equilateral.y, equilateral.z, equilateral.tau)

    assert results["x_expand_1"] == (
        sp.diff(equilateral.phi0(equilateral.tau), equilateral.tau)
        * sp.diff(delta, equilateral.tau)
        / equilateral.a(equilateral.tau) ** 2
    )
    assert results["x_expand_2"] == (
        sp.diff(delta, equilateral.tau) ** 2
        - sp.diff(delta, equilateral.x) ** 2
        - sp.diff(delta, equilateral.y) ** 2
        - sp.diff(delta, equilateral.z) ** 2
    ) / (2 * equilateral.a(equilateral.tau) ** 2)
    assert results["lag_3"] == (
        equilateral.a(equilateral.tau) ** 4
        * equilateral.delta_X1
        * (equilateral.PXXX * equilateral.delta_X1**2 + 6 * equilateral.PXX * equilateral.delta_X2)
        / 6
    )
    assert results["lag_0"] == equilateral.a(equilateral.tau) ** 4 * equilateral.P
    assert results["lag_1"] == equilateral.a(equilateral.tau) ** 4 * equilateral.PX * equilateral.delta_X1
    assert results["lag_2"] == equilateral.a(equilateral.tau) ** 4 * (
        equilateral.PX * equilateral.delta_X2 + equilateral.PXX * equilateral.delta_X1**2 / 2
    )


def test_equilateral_example_ports_third_order_delta_phi_and_zeta_cells():
    from examples import equilateral

    results = equilateral.main()
    delta = equilateral.delta_phi(equilateral.x, equilateral.y, equilateral.z, equilateral.tau)
    delta_t = sp.diff(delta, equilateral.tau)
    delta_grad_sq = sum(sp.diff(delta, coord) ** 2 for coord in (equilateral.x, equilateral.y, equilateral.z))
    expected_delta_phi = (
        equilateral.a(equilateral.tau)
        * equilateral.phi0_dot
        * (
            equilateral.PX**2
            * equilateral.lambda_
            * delta_t**3
            / (2 * equilateral.cs**4 * equilateral.Sigma**2)
            + equilateral.PX**2
            * (equilateral.cs**2 - 1)
            * delta_t
            * delta_grad_sq
            / (4 * equilateral.cs**4 * equilateral.Sigma)
        )
    )

    zeta_field = equilateral.zeta_field(equilateral.x, equilateral.y, equilateral.z, equilateral.tau)
    zeta_t = sp.diff(zeta_field, equilateral.tau)
    zeta_grad_sq = sum(sp.diff(zeta_field, coord) ** 2 for coord in (equilateral.x, equilateral.y, equilateral.z))
    expected_zeta = (
        -2 * equilateral.lambda_ * equilateral.a(equilateral.tau) * zeta_t**3 / equilateral.H**3
        + equilateral.Sigma
        * equilateral.a(equilateral.tau)
        * (1 - equilateral.cs**2)
        * zeta_t
        * zeta_grad_sq
        / equilateral.H**3
    )

    assert sp.simplify(results["lag3_delta_phi"] - expected_delta_phi) == 0
    assert sp.simplify(results["lag3_zeta"] - expected_zeta) == 0


def _implicit_index_label_counts(expr):
    counts = Counter()

    def visit(node, multiplier=1):
        node = sp.sympify(node)
        if isinstance(node, sp.Pow) and node.exp.is_Integer and node.exp > 0:
            visit(node.base, multiplier * int(node.exp))
            return
        if isinstance(node, Index) and node.head_name in {DN.name, UP.name}:
            counts[node.label] += multiplier
            return
        for arg in getattr(node, "args", ()):
            visit(arg, multiplier)

    visit(expr)
    return counts
